/*
 * This file is generated by jOOQ.
 */
package org.jooq.your.base;


import org.jooq.your.base.tables.Student;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.student</code>.
     */
    public static final Student STUDENT = Student.STUDENT;
}
