/*
 * This file is generated by jOOQ.
 */
package org.jooq.your.base.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.your.base.tables.Student;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentRecord extends UpdatableRecordImpl<StudentRecord> implements Record6<Integer, Integer, Integer, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.student.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.student.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.student.age</code>.
     */
    public void setAge(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.student.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.student.course</code>.
     */
    public void setCourse(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.student.course</code>.
     */
    public Integer getCourse() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.student.firstname</code>.
     */
    public void setFirstname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.student.firstname</code>.
     */
    public String getFirstname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.student.lastname</code>.
     */
    public void setLastname(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.student.lastname</code>.
     */
    public String getLastname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.student.secondname</code>.
     */
    public void setSecondname(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.student.secondname</code>.
     */
    public String getSecondname() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, Integer, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, Integer, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Student.STUDENT.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Student.STUDENT.AGE;
    }

    @Override
    public Field<Integer> field3() {
        return Student.STUDENT.COURSE;
    }

    @Override
    public Field<String> field4() {
        return Student.STUDENT.FIRSTNAME;
    }

    @Override
    public Field<String> field5() {
        return Student.STUDENT.LASTNAME;
    }

    @Override
    public Field<String> field6() {
        return Student.STUDENT.SECONDNAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAge();
    }

    @Override
    public Integer component3() {
        return getCourse();
    }

    @Override
    public String component4() {
        return getFirstname();
    }

    @Override
    public String component5() {
        return getLastname();
    }

    @Override
    public String component6() {
        return getSecondname();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAge();
    }

    @Override
    public Integer value3() {
        return getCourse();
    }

    @Override
    public String value4() {
        return getFirstname();
    }

    @Override
    public String value5() {
        return getLastname();
    }

    @Override
    public String value6() {
        return getSecondname();
    }

    @Override
    public StudentRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public StudentRecord value2(Integer value) {
        setAge(value);
        return this;
    }

    @Override
    public StudentRecord value3(Integer value) {
        setCourse(value);
        return this;
    }

    @Override
    public StudentRecord value4(String value) {
        setFirstname(value);
        return this;
    }

    @Override
    public StudentRecord value5(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public StudentRecord value6(String value) {
        setSecondname(value);
        return this;
    }

    @Override
    public StudentRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentRecord
     */
    public StudentRecord() {
        super(Student.STUDENT);
    }

    /**
     * Create a detached, initialised StudentRecord
     */
    public StudentRecord(Integer id, Integer age, Integer course, String firstname, String lastname, String secondname) {
        super(Student.STUDENT);

        setId(id);
        setAge(age);
        setCourse(course);
        setFirstname(firstname);
        setLastname(lastname);
        setSecondname(secondname);
        resetChangedOnNotNull();
    }
}
